name = "bluedoor-accounts"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
account_id = "e87173c892aeaf3f199a7728857f7c1b"

[[d1_databases]]
binding = "DB"
database_name = "bluedoor-db"
database_id = "ebaaa404-6232-4331-9d18-5d1bb5ec87cd"

[[kv_namespaces]]
binding = "SESSIONS"
id = "b91d11a00154490ebd4c4f8945b1a76c"

[vars]
GAS_URL = "https://script.google.com/macros/s/AKfycbwDHnYmCO9Z2Z-fsaSQUn5fTkN5GpBYXxqCKSILQZOkVsg_Yf5z5by6dpxKTEeLmLi9Fw/exec"
